# Automatically generated by pb2py
import protobuf as p
from .MoneroTsxData import MoneroTsxData


class MoneroTsxInit(p.MessageType):
    MESSAGE_WIRE_TYPE = 301
    FIELDS = {
        1: ('version', p.UVarintType, 0),
        2: ('tsx_data', MoneroTsxData, 0),
    }

    def __init__(
        self,
        version: int = None,
        tsx_data: MoneroTsxData = None
    ) -> None:
        self.version = version
        self.tsx_data = tsx_data
