# Automatically generated by pb2py
import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None
from .MoneroSubAddrIndicesList import MoneroSubAddrIndicesList


class MoneroKeyImageExportInit(p.MessageType):
    MESSAGE_WIRE_TYPE = 319
    FIELDS = {
        1: ('num', p.UVarintType, 0),
        2: ('hash', p.BytesType, 0),
        3: ('subs', MoneroSubAddrIndicesList, p.FLAG_REPEATED),
    }

    def __init__(
        self,
        num: int = None,
        hash: bytes = None,
        subs: List[MoneroSubAddrIndicesList] = None
    ) -> None:
        self.num = num
        self.hash = hash
        self.subs = subs if subs is not None else []
